timeout: "1600s" 
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
steps:

# Set build context to app dir
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/market-data/VaR-mc-bq:$COMMIT_SHA', '-f', 'python/Dockerfile', '.']

# Push image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/market-data/VaR-mc-bq:$COMMIT_SHA']

images: 
- 'us-central1-docker.pkg.dev/$PROJECT_ID/market-data/VaR-mc-bq:$COMMIT_SHA'